minecraft_version=1.21.1
yarn_mappings=1.21.1+build.1
loader_version=0.15.11
fabric_version=0.100.0+1.21.1
neoforge_version=21.1.64

mod_id=elementalsmorebendings
mod_version=1.0.0
mod_name=Elementals: More Bendings
mod_description=Addon para o mod Elementals adicionando sub-bendings de Gas, Plant, Mud e Crystal.
mod_authors=YourName
mod_license=MIT

maven_group=com.elementals.morebendings
archives_base_name=elementalsmorebendings
